In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/ethiopia.csv")

df.head()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M
0,2015,1,11.73,22.75,3.44,19.31,0.0,41.79,2.73,5.07,77.13,4.00
1,2015,2,12.30,24.01,4.09,19.92,0.0,33.29,2.39,4.19,77.14,3.35
2,2015,3,12.49,24.17,3.97,20.20,0.0,33.83,1.77,2.76,77.11,3.43
3,2015,4,14.08,23.78,6.90,16.88,0.0,38.84,0.87,1.28,77.07,4.60
4,2015,5,14.06,23.15,7.32,15.83,0.0,47.07,1.34,2.14,77.01,5.58

In [5]:
df["Country"] = "Ethiopia"

In [6]:
df["DATE"] = pd.to_datetime(df["YEAR"] * 1000 + df["DOY"], format="%Y%j")

In [7]:
df["MONTH"] = df["DATE"].dt.month

In [8]:
df = df.replace(-999, np.nan)

In [9]:
missing = df.isna().sum()
missing_pct = (missing / len(df)) * 100

missing_report = pd.DataFrame({
    "missing_values": missing,
    "missing_%": missing_pct
}).sort_values("missing_%", ascending=False)

missing_report

             missing_values  missing_%
YEAR                      0        0.0
DOY                       0        0.0
T2M                       0        0.0
T2M_MAX                   0        0.0
T2M_MIN                   0        0.0
T2M_RANGE                 0        0.0
PRECTOTCORR               0        0.0
RH2M                      0        0.0
WS2M                      0        0.0
WS2M_MAX                  0        0.0
PS                        0        0.0
QV2M                      0        0.0
Country                   0        0.0
DATE                      0        0.0
MONTH                     0        0.0

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()